[package]
name = "graft-search"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
graft-model = { path = "../graft-model" }
graft-i18n = { path = "../graft-i18n" }
serde.workspace = true
serde_json.workspace = true
memmap2.workspace = true
anyhow.workspace = true
