[package]
name = "archify-egui"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
eframe = ["dep:eframe"]
glow = ["dep:eframe", "eframe/glow"]
wgpu = ["dep:eframe", "eframe/wgpu"]

[dependencies]
archify-ir = { path = "../archify-ir" }
archify-geometry = { path = "../archify-geometry" }
egui.workspace = true
eframe = { workspace = true, optional = true }
