[package]
name = "graft-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
graft-model = { path = "../graft-model" }
lowlevel-sys = { path = "../lowlevel-sys" }
rayon.workspace = true
anyhow.workspace = true
serde.workspace = true
bincode.workspace = true
graft-cargo = { path = "../graft-cargo" }
graft-rust = { path = "../graft-rust" }
graft-langs = { path = "../graft-langs" }
graft-langs-link = { path = "../graft-langs-link" }
